version: '3.9'

services:
  nextjs:
    build: 
      context: ./
      dockerfile: Dockerfile

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80

# https://steveholgado.com/nginx-for-nextjs/