export const GET_SAMPLE = "GET_SAMPLE";
export const SAMPLE_ERROR = "SAMPLE_ERROR";

// Recipe actions
export const RECIPE_ERROR = "RECIPE_ERROR";
export const RECIPE_TOGGLE_FAVORITE = "RECIPE_TOGGLE_FAVORITE";
export const RECIPE_TOGGLED_FAVORITE = "RECIPE_TOGGLED_FAVORITE";
export const RECIPE_ADD_RECIPE = "RECIPE_ADD_RECIPE";
