export const GET_SAMPLE = "GET_SAMPLE";
export const SAMPLE_ERROR = "SAMPLE_ERROR";

// Recipe actions
export const RECIPE_ERROR = "RECIPE_ERROR";
export const RECIPE_TOGGLE_FAVORITE = "RECIPE_TOGGLE_FAVORITE";
export const RECIPE_TOGGLED_FAVORITE = "RECIPE_TOGGLED_FAVORITE";
export const RECIPE_ADD_RECIPE = "RECIPE_ADD_RECIPE";
export const RECIPE_REMOVE_RECIPE = "RECIPE_REMOVE_RECIPE";
export const RECIPE_RESET_RECIPES = "RECIPE_RESET_RECIPES";

// Auth actions
export const AUTH_SIGNIN = "AUTH_SIGNIN";
