name: Develop CI

on:
  pull_request:
    branches:
      - develop
      - feat/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Stage

    strategy:
      matrix:
        node-version: [16.x]

    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Run Build
        working-directory: ./
        run: yarn
